<?php
session_start();
// Check Auth
if (!isset($_SESSION['user_id'])) {
    header("Location: ../login.php");
    exit();
}
// Check ID
if (!isset($_GET['id'])) {
    header("Location: index.php");
    exit();
}

// Database and Models
require_once '../../app/Config/database.php';
require_once '../../app/Models/Room.php';

$room_id = intval($_GET['id']);
$user_id = $_SESSION['user_id'];

// Fetch Room Info using Model
$room = Room::findById($conn, $room_id);

if (!$room) {
    echo "Room not found.";
    exit();
}

// Check Access (Security)
if ($_SESSION['level'] < $room['min_level']) {
    header("Location: index.php");
    exit();
}

// Check if user has visited this room before
$visit_key = 'visited_room_' . $room_id;
$first_visit = !isset($_SESSION[$visit_key]);
if ($first_visit) {
    $_SESSION[$visit_key] = true;
}

// Fetch Artifacts & Collection Status using Model
$raw_artifacts = Room::getArtifacts($conn, $room_id, $user_id);

// Default positions for fallback
$fallback_positions = [
    ['top' => '60%', 'left' => '20%'],
    ['top' => '70%', 'left' => '50%'],
    ['top' => '55%', 'left' => '80%'],
    ['top' => '40%', 'left' => '30%'],
    ['top' => '50%', 'left' => '60%'],
];

$artifacts = [];
$collected_count = 0;
$i = 0;
foreach ($raw_artifacts as $row) {
    // specific positioning from DB or fallback
    if ($row['position_top'] && $row['position_left']) {
        $row['top'] = $row['position_top'];
        $row['left'] = $row['position_left'];
    } else {
        $pos = $fallback_positions[$i % count($fallback_positions)];
        $row['top'] = $pos['top'];
        $row['left'] = $pos['left'];
    }
    
    if ($row['is_collected'] > 0) $collected_count++;
    $artifacts[] = $row;
    $i++;
}

$total_artifacts = count($artifacts);
$all_collected = ($collected_count > 0 && $collected_count >= $total_artifacts);

// Check hidden artifact status using Model
$hidden_artifact_unlocked = Room::isHiddenArtifactUnlocked($conn, $room_id, $user_id);
$hidden_artifact = Room::getHiddenArtifact($conn, $room_id);
if ($hidden_artifact) {
    $hidden_artifact['unlocked'] = $hidden_artifact_unlocked;
}

// Clean description for JS usage
$desc = addslashes($room['description']);
$room_name = addslashes($room['name']);

include '../header.php';
include '../navbar.php';
?>

<!-- Room Intro Guide Modal - Improved Storytelling Style -->
<div id="guide-modal" class="fixed inset-0 z-[100] flex flex-col justify-end bg-black/80 backdrop-blur-md <?php echo $first_visit ? '' : 'hidden'; ?>">
    
    <!-- Professor Aldric - Direct child for proper z-index -->
    <div id="professor-container" class="absolute bottom-0 left-0 md:left-[-2rem] h-[125vh] w-[400px] z-30 pointer-events-none transition-all duration-700 ease-out flex items-end">
        <img id="prof-gif" src="/project-akhir/public/assets/img/professor.gif" alt="Professor Aldric" class="h-auto max-h-full w-auto object-contain object-bottom drop-shadow-[0_0_50px_rgba(197,160,89,0.3)] hidden">
        <img id="prof-idle" src="/project-akhir/public/assets/img/professor-diam.png" alt="Professor Aldric" class="h-auto max-h-full w-auto object-contain object-bottom drop-shadow-[0_0_50px_rgba(197,160,89,0.3)]">
    </div>
    
    <!-- Dialogue Area - Bottom -->
    <div class="relative w-full bg-black/95 border-t-2 border-gold z-20 p-6 pb-8 md:pl-[350px]">
        <!-- Guide Name Tag -->
        <div class="absolute -top-8 left-6 md:left-[350px] bg-gold text-black px-4 py-1 font-serif font-bold text-lg rounded-t shadow-[0_0_15px_rgba(197,160,89,0.5)]">
            Professor Aldric
        </div>
        
        <!-- Typewriter Text Container -->
        <div class="min-h-[80px] font-serif text-lg md:text-xl text-gray-200 leading-relaxed drop-shadow-md relative">
            <span id="typewriter-text"></span><span class="animate-pulse text-gold">|</span>
        </div>
        
        <!-- Controls -->
        <div class="flex justify-between items-center mt-6 border-t border-gray-800 pt-4">
            <div class="flex gap-2" id="dialog-dots">
                <!-- Dots generated by JS -->
            </div>
            
            <button id="btn-next" class="btn-museum bg-gold/10 hover:bg-gold text-gold hover:text-black">
                Next <i class="fas fa-chevron-right ml-2"></i>
            </button>
        </div>
        
        <!-- Skip Button -->
        <button id="btn-skip" class="absolute top-4 right-4 text-gray-500 hover:text-white text-sm uppercase tracking-wider">
            Skip Intro <i class="fas fa-forward ml-1"></i>
        </button>
    </div>
</div>

<!-- Info Button to reopen guide (fixed position) -->
<button id="btn-info" class="fixed top-20 right-4 z-[90] w-12 h-12 rounded-full bg-black/70 border-2 border-gold text-gold hover:bg-gold hover:text-black transition flex items-center justify-center shadow-lg">
    <i class="fas fa-book-open"></i>
</button>

<div class="relative w-full h-[calc(100vh-64px)] overflow-hidden bg-black">
    <!-- Navigation Buttons -->
    <div class="absolute top-4 left-4 z-30 flex gap-3">
        <a href="index.php" class="btn-museum bg-black/50 text-white border-white/30 hover:bg-gold hover:text-black">
            <i class="fas fa-arrow-left mr-2"></i> Back to Lobby
        </a>
        
        <a href="quiz.php?room_id=<?php echo $room_id; ?>" class="btn-museum bg-black/50 text-gold border-gold/50 hover:bg-gold hover:text-black">
            <i class="fas fa-question-circle mr-2"></i> Take Quiz
        </a>
    </div>
    
    <!-- Room Progress -->
    <div class="absolute top-4 right-20 z-30 flex items-center gap-2 bg-black/50 border border-gray-700 rounded-full px-4 py-2">
        <i class="fas fa-gem text-gold"></i>
        <span class="text-white text-sm"><?php echo $collected_count; ?>/<?php echo $total_artifacts; ?></span>
    </div>

    <!-- Room Background -->
    <div class="absolute inset-0 bg-cover bg-center z-0" 
         style="background-image: url('<?php echo $room['image_url']; ?>');">
        <!-- Vignette -->
        <div class="absolute inset-0 bg-radial-gradient"></div>
    </div>

    <!-- Interactive Artifacts -->
    <div class="relative w-full h-full z-10" id="artifact-container">
        <?php foreach ($artifacts as $artifact): ?>
            <?php $is_collected = $artifact['is_collected'] > 0; ?>
            <!-- Artifact Item - Fixed position, pulsing glow only -->
            <div class="absolute cursor-pointer transform group artifact-item"
                 data-id="<?php echo $artifact['id']; ?>"
                 data-name="<?php echo htmlspecialchars($artifact['name']); ?>"
                 data-desc="<?php echo htmlspecialchars($artifact['description']); ?>"
                 data-image="<?php echo htmlspecialchars($artifact['image_url']); ?>"
                 data-collected="<?php echo $is_collected ? 'true' : 'false'; ?>"
                 style="top: <?php echo $artifact['top']; ?>; left: <?php echo $artifact['left']; ?>;">
                    
                <!-- Artifact Container -->
                <div class="relative w-12 h-12 flex items-center justify-center transition duration-500 ease-out">
                    
                    <!-- 1. Outer Diffuse Glow - Large pulsing aurora -->
                    <div class="absolute inset-[-5px] rounded-full bg-gold/20 blur-xl animate-pulse group-hover:opacity-100 group-hover:bg-gold/60 group-hover:blur-2xl transition duration-500"></div>
                    
                    <!-- 2. Inner Focused Glow - Stronger light -->
                    <div class="absolute inset-1 rounded-full bg-gold/40 blur-md group-hover:bg-gold/80 group-hover:bg-opacity-100 transition duration-300"></div>
                    
                    <!-- 3. Core Light - The bright source -->
                    <div class="absolute w-1 h-1 bg-white rounded-full shadow-[0_0_10px_rgba(255,255,255,0.8)] group-hover:w-2 group-hover:h-2 group-hover:shadow-[0_0_30px_rgba(255,255,255,1)] transition-all duration-300"></div>

                </div>
                <!-- Tooltip removed for mystery -->
            </div>
        <?php endforeach; ?>
    </div>

    <?php include '../artifact_detail.php'; ?>
    
    <!-- Congratulation Dialog (Shows when all artifacts collected) - Same structure as intro -->
    <?php if ($all_collected): ?>
    <div id="congrats-modal" class="fixed inset-0 z-[100] hidden flex flex-col justify-end bg-black/90">
        <!-- Professor Container - Same as intro -->
        <div id="congrats-professor-container" class="absolute bottom-0 left-0 md:left-[-2rem] h-[125vh] w-[400px] z-30 pointer-events-none transition-all duration-700 ease-out flex items-end">
            <img id="congrats-prof-gif" src="/project-akhir/public/assets/img/professor.gif" alt="Professor Aldric" class="h-auto max-h-full w-auto object-contain object-bottom drop-shadow-[0_0_50px_rgba(197,160,89,0.3)] hidden">
            <img id="congrats-prof-idle" src="/project-akhir/public/assets/img/professor-diam.png" alt="Professor Aldric" class="h-auto max-h-full w-auto object-contain object-bottom drop-shadow-[0_0_50px_rgba(197,160,89,0.3)]">
        </div>
        
        <!-- Dialogue Area - Bottom (Same as intro) -->
        <div class="relative w-full bg-black/95 border-t-2 border-gold z-20 p-6 pb-8 md:pl-[350px]">
            <!-- Guide Name Tag -->
            <div class="absolute -top-8 left-6 md:left-[350px] bg-gold text-black px-4 py-1 font-serif font-bold text-lg rounded-t shadow-[0_0_15px_rgba(197,160,89,0.5)]">
                Professor Aldric
            </div>
            
            <!-- Typewriter Text Container -->
            <div class="min-h-[80px] font-serif text-lg md:text-xl text-gray-200 leading-relaxed drop-shadow-md relative">
                <span id="congrats-typewriter"></span><span class="animate-pulse text-gold">|</span>
            </div>
            
            <!-- Controls -->
            <div class="flex justify-between items-center mt-6 border-t border-gray-800 pt-4">
                <div class="flex gap-2" id="congrats-dots">
                    <!-- Dots generated by JS -->
                </div>
                
                <!-- Next Button -->
                <button id="congrats-next" class="btn-museum bg-gold/10 hover:bg-gold text-gold hover:text-black">
                    Next <i class="fas fa-chevron-right ml-2"></i>
                </button>
                
                <!-- Action Buttons (hidden initially, shown at last message) -->
                <div id="congrats-actions" class="hidden flex gap-4">
                    <a href="quiz.php?room_id=<?php echo $room_id; ?>" class="btn-museum bg-gold hover:bg-gold-hover text-black">
                        <i class="fas fa-check mr-2"></i> Yes, let's go!
                    </a>
                    <button id="congrats-no" class="btn-museum bg-transparent border-gray-500 text-gray-400 hover:text-white hover:border-white">
                        <i class="fas fa-times mr-2"></i> Maybe later
                    </button>
                </div>
            </div>
            
            <!-- Skip Button -->
            <button id="congrats-skip" class="absolute top-4 right-4 text-gray-500 hover:text-white text-sm uppercase tracking-wider">
                Skip <i class="fas fa-forward ml-1"></i>
            </button>
        </div>
    </div>
    <?php endif; ?>
</div>

<script>
document.addEventListener('DOMContentLoaded', () => {
    const guideModal = document.getElementById('guide-modal');
    const professorContainer = document.getElementById('professor-container');
    const profGif = document.getElementById('prof-gif');
    const profIdle = document.getElementById('prof-idle');
    const typewriterText = document.getElementById('typewriter-text');
    const btnNext = document.getElementById('btn-next');
    const btnSkip = document.getElementById('btn-skip');
    const btnInfo = document.getElementById('btn-info');
    const dialogDotsContainer = document.getElementById('dialog-dots');
    
    function restartProfessorAnimation() {
        // Simple fade animation
        professorContainer.style.opacity = '0';
        professorContainer.style.transform = 'translateX(-50px)';
        
        setTimeout(() => {
            professorContainer.style.opacity = '1';
            professorContainer.style.transform = 'translateX(0)';
        }, 100);
    }

    function setProfessorState(isTalking) {
        if (isTalking) {
            profGif.classList.remove('hidden');
            profIdle.classList.add('hidden');
        } else {
            profGif.classList.add('hidden');
            profIdle.classList.remove('hidden');
        }
    }
    
    // Dialog Data - Use database dialogs if available, otherwise fallback to defaults
    <?php 
    $db_dialogs = json_decode($room['professor_dialogs'] ?? '[]', true);
    $default_dialogs = [
        "Welcome, young explorer! I am Professor Aldric.",
        "You have entered the " . addslashes($room['name']) . ". A magnificent place, isn't it?",
        addslashes($room['description']),
        "There are " . $total_artifacts . " artifacts hidden here. Look for the glowing markers.",
        "Collect them all to gain knowledge and experience. Good luck!"
    ];
    $final_dialogs = !empty($db_dialogs) ? $db_dialogs : $default_dialogs;
    ?>
    const messages = <?php echo json_encode($final_dialogs); ?>;
    
    let currentStep = 0;
    let isTyping = false;
    let typeInterval;
    
    // Create dots
    messages.forEach((_, index) => {
        const dot = document.createElement('div');
        dot.className = `w-3 h-3 rounded-full ${index === 0 ? 'bg-gold' : 'bg-gray-600'} transition-colors duration-300`;
        dialogDotsContainer.appendChild(dot);
    });
    
    const dots = dialogDotsContainer.querySelectorAll('div');
    
    function updateDots(index) {
        dots.forEach((dot, i) => {
            dot.classList.toggle('bg-gold', i === index);
            dot.classList.toggle('bg-gray-600', i !== index);
        });
    }

    function typeText(text, callback) {
        isTyping = true;
        setProfessorState(true); // Talking
        typewriterText.innerHTML = "";
        let i = 0;
        clearInterval(typeInterval);
        
        typeInterval = setInterval(() => {
            if (i < text.length) {
                typewriterText.textContent += text.charAt(i);
                i++;
            } else {
                clearInterval(typeInterval);
                isTyping = false;
                setProfessorState(false); // Idle
                if (callback) callback();
            }
        }, 30); // Speed: 30ms per char
    }
    
    function showMessage(index) {
        if (index >= messages.length) {
            closeGuide();
            return;
        }

        // Restart Professor Animation on every step
        restartProfessorAnimation();
        
        updateDots(index);
        
        if (index === messages.length - 1) {
            btnNext.innerHTML = 'Start Exploring <i class="fas fa-play ml-2"></i>';
        } else {
            btnNext.innerHTML = 'Next <i class="fas fa-chevron-right ml-2"></i>';
        }
        
        typeText(messages[index]);
    }
    
    function instantFinish() {
        clearInterval(typeInterval);
        typewriterText.textContent = messages[currentStep];
        isTyping = false;
        setProfessorState(false); // Idle
    }
    
    function nextStep() {
        if (isTyping) {
            instantFinish();
        } else {
            currentStep++;
            showMessage(currentStep);
        }
    }
    
    function closeGuide() {
        guideModal.classList.add('opacity-0');
        setTimeout(() => guideModal.classList.add('hidden'), 500);
    }
    
    function openGuide() {
        currentStep = 0;
        guideModal.classList.remove('hidden');
        // Small delay to allow fade-in transition if added later
        setTimeout(() => {
            guideModal.classList.remove('opacity-0');
            showMessage(0);
        }, 10);
    }
    
    // Event Listeners
    btnNext.addEventListener('click', nextStep);
    
    // Allow clicking on text area to speed up
    const textArea = guideModal.querySelector('.min-h-\\[80px\\]');
    if (textArea) {
        textArea.addEventListener('click', () => {
            if (isTyping) instantFinish();
        });
    }

    btnSkip.addEventListener('click', closeGuide);
    btnInfo.addEventListener('click', openGuide);
    
    // Enter key to advance dialog
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') {
            if (guideModal && !guideModal.classList.contains('hidden')) {
                e.preventDefault();
                nextStep();
            } else if (congratsModal && !congratsModal.classList.contains('hidden')) {
                // Only if next button is visible (not on Yes/No step)
                if (congratsNext && !congratsNext.classList.contains('hidden')) {
                    e.preventDefault();
                    nextCongratsStep();
                }
            }
        }
    });
    
    // Start if first visit or manually opened
    if (!guideModal.classList.contains('hidden')) {
        showMessage(0);
    }
    
    // Add animations styles
    const style = document.createElement('style');
    style.textContent = `
        @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(50px); }
            to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in-up {
            animation: fadeInUp 0.8s ease-out forwards;
        }
    `;
    document.head.appendChild(style);
    
    // Congrats Dialog Logic (Typewriter style)
    const congratsModal = document.getElementById('congrats-modal');
    const congratsTypewriter = document.getElementById('congrats-typewriter');
    const congratsDots = document.getElementById('congrats-dots');
    const congratsNext = document.getElementById('congrats-next');
    const congratsActions = document.getElementById('congrats-actions');
    const congratsNo = document.getElementById('congrats-no');
    
    // Check if should show congrats
    const allCollected = <?php echo $all_collected ? 'true' : 'false'; ?>;
    const congratsShown = sessionStorage.getItem('congrats_shown_room_<?php echo $room_id; ?>');
    
    // Congrats messages
    const congratsMessages = [
        "🎉 Incredible work, young explorer!",
        "You have successfully collected all <?php echo $total_artifacts; ?> artifacts in the <?php echo addslashes($room['name']); ?>!",
        "But wait... I sense something else hidden in this chamber...",
        "There is a secret artifact here, but its name remains unknown to me.",
        "To reveal its identity, you must prove your knowledge by completing the quiz.",
        "Are you ready to take the challenge?"
    ];
    
    let congratsStep = 0;
    let congratsTyping = false;
    let congratsTypeInterval;
    
    // Create dots
    if (congratsDots) {
        congratsMessages.forEach((_, index) => {
            const dot = document.createElement('div');
            dot.className = `w-2 h-2 rounded-full ${index === 0 ? 'bg-gold' : 'bg-gray-600'} transition-colors duration-300`;
            congratsDots.appendChild(dot);
        });
    }
    
    const congratsDotElements = congratsDots ? congratsDots.querySelectorAll('div') : [];
    
    function updateCongratsDots(index) {
        congratsDotElements.forEach((dot, i) => {
            dot.className = `w-2 h-2 rounded-full ${i <= index ? 'bg-gold' : 'bg-gray-600'} transition-colors duration-300`;
        });
    }
    
    const congratsProfGif = document.getElementById('congrats-prof-gif');
    const congratsProfIdle = document.getElementById('congrats-prof-idle');

    function setCongratsProfessorState(isTalking) {
        if (congratsProfGif && congratsProfIdle) {
            if (isTalking) {
                congratsProfGif.classList.remove('hidden');
                congratsProfIdle.classList.add('hidden');
            } else {
                congratsProfGif.classList.add('hidden');
                congratsProfIdle.classList.remove('hidden');
            }
        }
    }

    function typeCongratsMessage(text, callback) {
        congratsTyping = true;
        setCongratsProfessorState(true); // Start Talking
        let i = 0;
        congratsTypewriter.innerHTML = '';
        
        congratsTypeInterval = setInterval(() => {
            if (i < text.length) {
                congratsTypewriter.innerHTML += text.charAt(i);
                i++;
            } else {
                clearInterval(congratsTypeInterval);
                congratsTyping = false;
                setCongratsProfessorState(false); // Stop Talking (Idle)
                if (callback) callback();
            }
        }, 30);
    }
    
    function showCongratsMessage(index) {
        if (index >= congratsMessages.length) {
            // Show Yes/No buttons on last message
            congratsNext.classList.add('hidden');
            congratsActions.classList.remove('hidden');
            setCongratsProfessorState(false); // Ensure idle
            return;
        }
        
        congratsStep = index;
        updateCongratsDots(index);
        typeCongratsMessage(congratsMessages[index]);
    }
    
    function nextCongratsStep() {
        if (congratsTyping) {
            clearInterval(congratsTypeInterval);
            congratsTypewriter.innerHTML = congratsMessages[congratsStep];
            congratsTyping = false;
            setCongratsProfessorState(false); // Stop Talking (Idle)
        } else {
            showCongratsMessage(congratsStep + 1);
        }
    }
    
    function showCongratsModal() {
        if (congratsModal && !congratsShown) {
            congratsModal.classList.remove('hidden');
            setTimeout(() => {
                congratsModal.classList.remove('opacity-0');
                showCongratsMessage(0);
            }, 100);
            sessionStorage.setItem('congrats_shown_room_<?php echo $room_id; ?>', 'true');
        }
    }
    
    function hideCongratsModal() {
        if (congratsModal) {
            congratsModal.classList.add('hidden');
        }
    }
    
    if (congratsNext) {
        congratsNext.addEventListener('click', nextCongratsStep);
    }
    
    if (congratsNo) {
        congratsNo.addEventListener('click', hideCongratsModal);
    }
    
    // Skip button
    const congratsSkip = document.getElementById('congrats-skip');
    if (congratsSkip) {
        congratsSkip.addEventListener('click', hideCongratsModal);
    }
    // Show congrats modal after guide is closed (if all collected)
    console.log('DEBUG: allCollected=', allCollected, 'congratsShown=', congratsShown, 'modal=', congratsModal);
    
    if (allCollected && !congratsShown) {
        // If guide is shown, wait for it to close
        if (guideModal && !guideModal.classList.contains('hidden')) {
            // Modify closeGuide to also trigger congrats
            const originalCloseGuide = closeGuide;
            closeGuide = function() {
                originalCloseGuide();
                setTimeout(showCongratsModal, 500);
            };
        } else {
            // Guide already closed, show congrats after short delay
            setTimeout(showCongratsModal, 1000);
        }
    }
});
</script>


